### ISSUE TITLE
Refactor profile generation

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/krf#2]
Right now, `krfctl` gets its profiles from a `profiles.yml` file that looks like this:

```yaml
fs:
  - read
  - write
  # ...
```

This is annoying to maintain: we have to update each profile manually whenever new syscalls are added. To resolve this, we should integrate profiles into the syscall definition files.

Old:

```yaml
# chdir.yml
proto: const char __user *filename
parms: filename
errors:
  - EACCES
  - EFAULT
  # ...
```

New:

```yml
# chdir.yml
proto: const char __user *filename
parms: filename
errors:
  - EACCES
  - EFAULT
  # ...
profiles:
  - fs
  # ...
```
